### ISSUE TITLE
クレカの初期データ作成

### ISSUE THREAD

**Issue by kushikushi5969** [kushikushi5969/next-admin-prisma#7]
**Is your feature request related to a problem? Please describe.**
クレジットカードの初期データを作成する。

**Describe the solution you'd like**
seed.tsでfetchした情報を格納する。

1. seed.tsの作成
```typescript
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Node.jsの組み込みfetchを使用
  const response = await fetch('https://api.example.com/data');
  const data = await response.json();

  // 取得したデータの各項目をデータベースに挿入
  for (const item of data) {
    await prisma.exampleModel.create({
      data: {
        // モデルのフィールドに合わせてデータをマッピング
        name: item.name,
        description: item.description,
        // その他のフィールド...
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```
2. ts-nodeのインストール
seed.ts(TypescriptをNode.jsで直接実行できる様にする
```shell
npm install ts-node --save-dev
```
3. Prismaのシードスクリプトを設定する
```json
# package.json
{
  // 中略
  "prisma": {
    "seed": "ts-node prisma/seed.ts"
  }
}

```
5. 実行
```shell
npx prisma db seed
```

**Comment by kushikushi5969** [comment]
## エラー`SyntaxError: Cannot use import statement outside a module`
`npx prisma db seed`実行時にエラー発生。
```shell
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module.m._compile (/Users/hogesan/Desktop/next-admin-prisma/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hogesan/Desktop/next-admin-prisma/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at phase4 (/Users/hogesan/Desktop/next-admin-prisma/node_modules/ts-node/src/bin.ts:649:14)
```

## 原因
Node.jsがimport文をESモジュールとして解釈できない場合に発生するとのこと。

## 解決
モジュールを明示的に有効にする。
以下を実行。
```shell
npx ts-node --compiler-options '{"module":"CommonJS"}' prisma/seed.ts
```
